use std::fs;
use std::path::{Path, PathBuf};

use chrono::NaiveDate;

use crate::analyzer::{self, AnalysisContext};
use crate::config;
use crate::history;

pub fn run(id: String, provider: Option<String>, force: bool) -> Result<(), String> {
    let config_dir = std::env::current_dir().map_err(|e| e.to_string())?;
    let cfg = config::load(&config_dir)?;
    let problem_id = config::ProblemId::parse(&id);
    let problem_dir = config::resolve_problem_folder(&config_dir, &cfg, &problem_id)?;

    let analysis_path = problem_dir.join("analysis.md");
    if analysis_path.exists() && !force {
        return Err("analysis.md already exists — use --force to overwrite".to_string());
    }

    let question = fs::read_to_string(problem_dir.join("question.md"))
        .unwrap_or_else(|_| "No question.md found".to_string());

    let solution = read_latest_solution(&problem_dir)?;
    let transcripts = read_transcripts(&problem_dir);

    if transcripts.is_empty() {
        return Err(format!(
            "no transcripts found in {}. run `rak transcribe {}` first.",
            id, id
        ));
    }

    let provider_name = provider
        .as_deref()
        .unwrap_or(&cfg.analyze.default_provider);
    let provider_config = cfg.analyze.providers.get(provider_name);
    let json_config = provider_config
        .map(|pc| serde_json::json!({ "model": pc.model }))
        .unwrap_or(serde_json::Value::Null);

    let analyzer = analyzer::get(provider_name, &json_config)?;

    println!("Analyzing {}...", id);
    let ctx = AnalysisContext {
        question,
        solution,
        transcripts,
    };

    let result = analyzer.analyze(&cfg.analyze.system_prompt, &ctx)?;

    fs::write(&analysis_path, &result).map_err(|e| format!("failed to write analysis.md: {e}"))?;
    println!("✓ Saved {}", analysis_path.display());

    let leetcode_dir = config_dir.join(&cfg.leetcode_dir);
    let history_path = config_dir.join("history.yaml");
    let rak_toml_dir = config::find_rak_toml(&config_dir)
        .ok()
        .and_then(|p| p.parent().map(|d| d.to_path_buf()))
        .unwrap_or_else(|| config_dir.clone());
    rebuild_master(&leetcode_dir, &history_path, &rak_toml_dir)?;

    Ok(())
}

const MASTER_INTRO: &str = r#"# Leetcode Skill Report

This file is auto-generated by `rak analyze`. It stitches together all problem
analyses, sorted by most recent attempt, so an AI assistant can assess current
coding strengths and weaknesses from a single document.

## How the Leitner System Works

Problems are sorted into 5 boxes based on self-assessed performance:

| Box | Review interval | Meaning      |
|-----|-----------------|--------------|
|  1  | Every 1 day     | Struggling   |
|  2  | Every 3 days    |              |
|  3  | Every 7 days    |              |
|  4  | Every 14 days   |              |
|  5  | Every 30 days   | Mastered     |

- Rating 4–5 → move up one box
- Rating 3 → stay in current box
- Rating 1–2 → reset to Box 1
- Three consecutive rating-5s → jump straight to Box 5"#;

struct ProblemEntry {
    title: String,
    box_num: u8,
    last_date: NaiveDate,
    analysis: String,
}

fn rebuild_master(leetcode_dir: &Path, history_path: &Path, master_dir: &Path) -> Result<(), String> {
    let hist = history::load(history_path)?;

    let mut entries: Vec<ProblemEntry> = Vec::new();

    let rd = fs::read_dir(leetcode_dir)
        .map_err(|e| format!("failed to read leetcode_dir: {e}"))?;

    for entry in rd.flatten() {
        let path = entry.path();
        if !path.is_dir() {
            continue;
        }
        let analysis_path = path.join("analysis.md");
        if !analysis_path.exists() {
            continue;
        }

        let folder_name = match path.file_name().and_then(|n| n.to_str()) {
            Some(n) => n.to_string(),
            None => continue,
        };

        let analysis = match fs::read_to_string(&analysis_path) {
            Ok(s) => s,
            Err(_) => continue,
        };

        let key = folder_to_history_key(&folder_name);
        let hist_entry = hist.problems.get(&key);

        let title = hist_entry
            .and_then(|p| p.title.as_deref())
            .map(|t| format!("{folder_name} — {t}"))
            .unwrap_or_else(|| folder_name.clone());

        let box_num = hist_entry.map(|p| p.box_num).unwrap_or(1);

        let last_date = hist_entry
            .map(|p| p.last_review)
            .unwrap_or_else(|| mtime_as_date(&analysis_path));

        entries.push(ProblemEntry { title, box_num, last_date, analysis });
    }

    // Most recent first
    entries.sort_by(|a, b| b.last_date.cmp(&a.last_date));

    let mut parts: Vec<String> = Vec::with_capacity(entries.len() + 1);
    parts.push(MASTER_INTRO.to_string());

    for e in &entries {
        parts.push(format!(
            "## {} | Box {} | Last attempt: {}\n\n{}",
            e.title,
            e.box_num,
            e.last_date,
            e.analysis.trim_end()
        ));
    }

    let content = parts.join("\n\n---\n\n") + "\n";

    let master_path = master_dir.join("analyses-master.md");
    fs::write(&master_path, content)
        .map_err(|e| format!("failed to write analyses-master.md: {e}"))?;
    println!("✓ Updated {}", master_path.display());

    Ok(())
}

fn folder_to_history_key(folder_name: &str) -> String {
    // "0001.two-sum" → "1"  (matches the key used by `rak log`)
    // "c3ai-strings" → "c3ai-strings"
    if let Some(dot_pos) = folder_name.find('.') {
        if let Ok(n) = folder_name[..dot_pos].parse::<u32>() {
            return n.to_string();
        }
    }
    folder_name.to_string()
}

fn mtime_as_date(path: &Path) -> NaiveDate {
    fs::metadata(path)
        .and_then(|m| m.modified())
        .map(|t| {
            let secs = t
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap_or_default()
                .as_secs();
            chrono::DateTime::from_timestamp(secs as i64, 0)
                .unwrap_or_default()
                .date_naive()
        })
        .unwrap_or_else(|_| chrono::Local::now().date_naive())
}

fn read_transcripts(dir: &Path) -> Vec<String> {
    let re = regex::Regex::new(r"^attempt-(\d+)\.md$").unwrap();
    let mut entries = Vec::new();
    if let Ok(rd) = fs::read_dir(dir) {
        for entry in rd.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            if let Some(caps) = re.captures(&name) {
                let n = caps[1].parse::<usize>().unwrap_or(0);
                if let Ok(content) = fs::read_to_string(entry.path()) {
                    entries.push((n, content));
                }
            }
        }
    }
    entries.sort_by_key(|(n, _)| *n);
    entries.into_iter().map(|(_, content)| content).collect()
}

fn read_latest_solution(dir: &Path) -> Result<String, String> {
    let extensions = [
        ".cpp", ".py", ".go", ".java", ".rs", ".js", ".ts", ".c", ".cs",
    ];
    let mut best: Option<(std::time::SystemTime, PathBuf)> = None;

    if let Ok(rd) = fs::read_dir(dir) {
        for entry in rd.flatten() {
            let path = entry.path();
            if path.is_file() {
                if let Some(ext) = path.extension() {
                    let ext_str = format!(".{}", ext.to_string_lossy());
                    if extensions.contains(&ext_str.as_str()) {
                        if let Ok(metadata) = entry.metadata() {
                            let mod_time = metadata
                                .modified()
                                .unwrap_or(std::time::SystemTime::UNIX_EPOCH);
                            if best.is_none() || mod_time > best.as_ref().unwrap().0 {
                                best = Some((mod_time, path));
                            }
                        }
                    }
                }
            }
        }
    }

    let solution_path = best
        .map(|(_, p)| p)
        .ok_or_else(|| "no solution file found".to_string())?;
    fs::read_to_string(solution_path).map_err(|e| format!("failed to read solution file: {e}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn test_read_transcripts_sorting() {
        let dir = tempfile::tempdir().unwrap();
        fs::write(dir.path().join("attempt-2.md"), "second").unwrap();
        fs::write(dir.path().join("attempt-1.md"), "first").unwrap();
        fs::write(dir.path().join("attempt-10.md"), "tenth").unwrap();
        fs::write(dir.path().join("other.txt"), "other").unwrap();

        let transcripts = read_transcripts(dir.path());
        assert_eq!(transcripts.len(), 3);
        assert_eq!(transcripts[0], "first");
        assert_eq!(transcripts[1], "second");
        assert_eq!(transcripts[2], "tenth");
    }

    #[test]
    fn test_read_latest_solution() {
        let dir = tempfile::tempdir().unwrap();
        let old_path = dir.path().join("solution.py");
        let new_path = dir.path().join("solution.cpp");

        fs::write(&old_path, "old").unwrap();
        // Ensure new_path has a later modification time
        std::thread::sleep(std::time::Duration::from_millis(100));
        fs::write(&new_path, "new").unwrap();

        let content = read_latest_solution(dir.path()).unwrap();
        assert_eq!(content, "new");
    }

    #[test]
    fn test_read_latest_solution_no_files() {
        let dir = tempfile::tempdir().unwrap();
        let res = read_latest_solution(dir.path());
        assert!(res.is_err());
        assert!(res.unwrap_err().contains("no solution file found"));
    }

    #[test]
    fn folder_to_history_key_numeric() {
        assert_eq!(folder_to_history_key("0001.two-sum"), "1");
        assert_eq!(folder_to_history_key("0042.trapping-rain-water"), "42");
        assert_eq!(folder_to_history_key("0200.number-of-islands"), "200");
    }

    #[test]
    fn folder_to_history_key_custom() {
        assert_eq!(folder_to_history_key("c3ai-strings"), "c3ai-strings");
        assert_eq!(folder_to_history_key("bloomberg-design"), "bloomberg-design");
    }

    #[test]
    fn rebuild_master_creates_file() {
        let tmp = tempfile::tempdir().unwrap();
        let lc = tmp.path().join("leetcode");

        // Two problem folders with analysis.md
        let p1 = lc.join("0001.two-sum");
        let p2 = lc.join("0042.trapping-rain-water");
        fs::create_dir_all(&p1).unwrap();
        fs::create_dir_all(&p2).unwrap();
        fs::write(p1.join("analysis.md"), "Analysis of two sum.").unwrap();
        std::thread::sleep(std::time::Duration::from_millis(50));
        fs::write(p2.join("analysis.md"), "Analysis of trapping rain water.").unwrap();

        let history_path = tmp.path().join("history.yaml");
        rebuild_master(&lc, &history_path, tmp.path()).unwrap();

        let master = fs::read_to_string(tmp.path().join("analyses-master.md")).unwrap();
        assert!(master.contains("# Leetcode Skill Report"));
        assert!(master.contains("Leitner"));
        assert!(master.contains("0042.trapping-rain-water"));
        assert!(master.contains("0001.two-sum"));
        assert!(master.contains("Analysis of two sum."));
        // trapping-rain-water was written later, so it should appear before two-sum
        let pos_42 = master.find("0042.trapping-rain-water").unwrap();
        let pos_1 = master.find("0001.two-sum").unwrap();
        assert!(pos_42 < pos_1, "more recent problem should appear first");
    }

    #[test]
    fn rebuild_master_skips_folders_without_analysis() {
        let tmp = tempfile::tempdir().unwrap();
        let lc = tmp.path().join("leetcode");
        let p1 = lc.join("0001.two-sum");
        let p2 = lc.join("0002.add-two-numbers");
        fs::create_dir_all(&p1).unwrap();
        fs::create_dir_all(&p2).unwrap();
        fs::write(p1.join("analysis.md"), "Has analysis.").unwrap();
        // p2 has no analysis.md

        let history_path = tmp.path().join("history.yaml");
        rebuild_master(&lc, &history_path, tmp.path()).unwrap();

        let master = fs::read_to_string(tmp.path().join("analyses-master.md")).unwrap();
        assert!(master.contains("0001.two-sum"));
        assert!(!master.contains("0002.add-two-numbers"));
    }
}
